-- Workspace Drive: the content grab link + the files it collects.
-- Table names come from @@map (workspace_upload_links / workspace_uploads).
-- DDL generated by `prisma migrate diff --from-empty --to-schema` and copied verbatim.

CREATE TABLE "workspace_upload_links" (
    "id" TEXT NOT NULL,
    "token" TEXT NOT NULL,
    "label" TEXT,
    "workspaceId" TEXT NOT NULL,
    "expiresAt" TIMESTAMP(3),
    "revokedAt" TIMESTAMP(3),
    "createdById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "workspace_upload_links_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "workspace_uploads" (
    "id" TEXT NOT NULL,
    "workspaceId" TEXT NOT NULL,
    "linkId" TEXT,
    "objectKey" TEXT NOT NULL,
    "displayName" TEXT NOT NULL,
    "contentType" TEXT NOT NULL,
    "size_bytes" BIGINT NOT NULL DEFAULT 0,
    "uploaderName" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "workspace_uploads_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "workspace_upload_links_token_key" ON "workspace_upload_links"("token");
CREATE INDEX "workspace_upload_links_workspaceId_idx" ON "workspace_upload_links"("workspaceId");
CREATE UNIQUE INDEX "workspace_uploads_objectKey_key" ON "workspace_uploads"("objectKey");
CREATE INDEX "workspace_uploads_workspaceId_idx" ON "workspace_uploads"("workspaceId");
CREATE INDEX "workspace_uploads_workspaceId_createdAt_idx" ON "workspace_uploads"("workspaceId", "createdAt" DESC);
CREATE INDEX "workspace_uploads_linkId_idx" ON "workspace_uploads"("linkId");

ALTER TABLE "workspace_upload_links" ADD CONSTRAINT "workspace_upload_links_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "workspace_uploads" ADD CONSTRAINT "workspace_uploads_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "workspace_uploads" ADD CONSTRAINT "workspace_uploads_linkId_fkey" FOREIGN KEY ("linkId") REFERENCES "workspace_upload_links"("id") ON DELETE SET NULL ON UPDATE CASCADE;
